src/Sharpliner.Model/GHActions/Permissions.cs
src/Sharpliner.Model/GHActions/Workflow.cs
tests/Sharpliner.Model.Tests/GitHub/WorkflowTests.cs

Allow to set the persmissions for a workflow, there are several ways to
use the API.
1. Provide each scope we want to Read or Write
```csharp
Permissions =
{
Write =
{
GitHubPermissionScope.Actions,
},
Read = {
GitHubPermissionScope.Actions,
GitHubPermissionScope.Contents
}
}
```
2. Read All
Use the fluent API
```csharp
Permissions = new Permissions().All(GitHubPermission.Read)
```
3. Write All
Use the fluent API
```csharp
Permissions = new Permissions().All(GitHubPermission.Write)
```
4. Read and Write All
Use the fluent API
```csharp
Permissions = new Permissions().All(GitHubPermission.Write).All(GitHubPermission.Read)
```
5. A mix of Read/Write All and more specific
Use a mix of declarative + fluet:
```csharp
Permissions = new Permissions
{
Read =
{
GitHubPermissionScope.Actions,
} …
```

[Model] GithubAction - Add permissions to the workflow.

---

azure-pipelines.yml
src/Sharpliner.Tools/PublishPipelines.cs
src/Sharpliner/AzureDevOps/AzureDevOpsPipelineDefinition.cs
src/Sharpliner/PipelineDefinitionBase.cs

```
D:\github\Sharpliner\eng\Sharpliner.CI
λ  dotnet build
Microsoft (R) Build Engine version 16.10.0-preview-21181-07+073022eb4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
Determining projects to restore...
All projects are up-to-date for restore.
Sharpliner.CI -> D:\github\Sharpliner\artifacts\bin\Sharpliner.CI\net5.0\Sharpliner.CI.dll
Publishing all pipeline definitions inside D:\github\Sharpliner\artifacts\bin\Sharpliner.CI\net5.0\Sharpliner.CI.dll
Publishing pipeline SharplinerPipeline to D:\github\Sharpliner\azure-pipelines.yml
Published new changes for SharplinerPipeline
Build succeeded.
0 Warning(s)
0 Error(s)
```

Report target YAML path and whether there were changes during publishing

---

eng/pipelines/pr.yml
eng/pipelines/publish.yml
eng/pipelines/templates/install-dotnet.yml
src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedExtensions.cs
src/Sharpliner/PipelineDefinitionBase.cs
tests/Sharpliner.Tests/AzureDevOps/Pipelines/XHarnessPipeline.cs
tests/Sharpliner.Tests/GitHub/JobTests.cs

- `And()`/`Or()` conditions now accept strings so things `And("succeeded()", IsPullRequest)` is possible
- No more trailing spaces in yaml headers
- Remove `Template<T>()` extension method to force using APIs such as `StepTemplate()`/`JobTemplate()`
- Create full path when publishing pipelines

AzureDevOps API improvements and publishing fixes

---

src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/PipelineDefinition.cs
src/Sharpliner/DefinitionBase.cs
src/Sharpliner/GitHubActions/GitHubActionsPipelineDefinition.cs
src/Sharpliner/PublishDefinitions.cs
src/Sharpliner/build/Sharpliner.props
src/Sharpliner/build/Sharpliner.targets

Often, we use the word "Pipelines" but not all objects defined via Sharpliner are pipelines, some are templates and there will be more 
No functional change, just preparing ground for upcoming changes

Rename Pipelines to Definitions

---

src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionBuilder.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs

Implements APIs for following expressions:
- `startsWith`, `endsWith`, `in`, `notIn`, `contains`, `containsValue`, `xor`, `lt`, `gt`

Add missing APIs for condition expressions

---

docs/AzureDevOps/DefinitionLibraries.md
src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedExtensions.cs
src/Sharpliner/AzureDevOps/DefinitionLibrary.cs

You can also pass a list of items to the methods that reference libraries and get those expanded without the need to declare a new library class.
```csharp
...
new Job("Build")
{
Steps =
{
Script.Inline("echo 'Hello World'"),
ExpandSteps(new[] { "5.0.403", "6.0.100" }.Select(version => DotNet.Install.Sdk(version))),
Script.Inline("echo 'Goodbye World'"),
}
}
...
```

Enable adding items instead of a full library too

---

src/Sharpliner/build/Sharpliner.targets

Call `dotnet build` when building in Visual Studio

---

src/Sharpliner/AzureDevOps/Pipeline.cs
tests/Sharpliner.Tests/AzureDevOps/Model/TriggerSerializationTests.cs

[AzureDevOps] Fix YAML property `schedule` to `schedules`

---

src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/BashTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/PowerShellTask.cs
tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/BashFileTaskTests.cs
tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/PowerShellFileTaskTests.cs
tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs

Fixes #168 
A little bit unfortunate solution but I found no other better. I wanted to preserve the nice `powershell: inline script` notation so I make an exemption when serializing the tasks that reference a script file so that they serialize as the full task invocations

Fix PowerShell and Bash tasks when referencing script files

---

src/Sharpliner/PublishDefinitions.cs

This will enable cases where we only want to create a definition NuGet that will be used in other Sharpliner projects (#175)

Do not fail the build when no definitions found

---

src/Sharpliner/PublishDefinitions.cs

Load all project assemblies when publishing pipelines

---

eng/Sharpliner.CI/ProjectBuildSteps.cs
eng/Sharpliner.CI/PublishPipeline.cs
eng/Sharpliner.CI/PullRequestPipeline.cs
eng/pipelines/pr.yml
eng/pipelines/publish.yml
src/Sharpliner/PublishDefinitions.cs
tests/NuGet.Tests/NuGet.config
tests/NuGet.Tests/NuGetWithBasePipeline/BasePipelineFromNuGet.cs
tests/NuGet.Tests/NuGetWithBasePipeline/NuGetWithBasePipeline.csproj
tests/NuGet.Tests/ProjectUsingTheNuGet/NuGetTestDefinition.cs
tests/NuGet.Tests/ProjectUsingTheNuGet/ProjectUsingTheNuGet.csproj
tests/NuGet.Tests/README.md

These NuGet.Tests are E2E testing following scenario:
1. We create a "library" project with some Sharpliner definition
2. We publish a .nupkg of this library project
3. We reference this .nupkg in another project
This is testing that all the referenced DLLs are loaded well even for this transitive scenario.
This is testing user scenarios where people want to publish definitions in the form of NuGet and re-use it in other projects.
Related to #175

Add E2E tests for .nupkg library scenario

---

src/Sharpliner/PublishDefinitions.cs
src/Sharpliner/SharplinerPublisher.cs

Loads the `Sharpliner.dll` that is in user's app and calls its `Publish()` instead of calling it from the NuGet one.
This means we can work with interfaces directly when instantiating definitions.
Resolves #179 into a state that I am happy with

Move definition look-up into LoadFrom binding context

---

src/Sharpliner/AzureDevOps/PipelineDefinition.cs
src/Sharpliner/AzureDevOps/PipelineDefinitionCollection.cs
src/Sharpliner/AzureDevOps/TemplateDefinition.cs
src/Sharpliner/AzureDevOps/TemplateDefinitionCollection.cs
src/Sharpliner/ISharplinerDefinition.cs
src/Sharpliner/SharplinerPublisher.cs

Previously, the logic was in the interface because we had issues with binding context (#179). Now we can afford to keep it more as data model only

Move logic out of `ISharplinerDefinition`

---

src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/Parameter.cs
src/Sharpliner/AzureDevOps/Pipeline.cs
src/Sharpliner/AzureDevOps/TemplateDefinition.cs
src/Sharpliner/AzureDevOps/TemplateDefinitionCollection.cs
tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs

Related to the discussion in #208:
- Internal rename of classes since we use parameters even in pipelines and not just templates
- Make display name optional for pipeline parameters

Rename `TemplateParameter` to `Parameter`

---

docs/AzureDevOps/DefinitionReference.md
src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/Builders/DownloadTaskBuilder.cs
src/Sharpliner/AzureDevOps/Model/Tasks/DownloadTask.cs
src/Sharpliner/MultilineStringEmitter.cs
src/Sharpliner/SharplinerSerializer.cs
tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs

- When specifying the `download: none` and `download: current`, uses the shorthand YAML style
https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-download?view=azure-pipelines
- When utilizing specific build / latest from branch, uses the full task with all available properties
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops
- Improves the builder for better UX
Fixes #202

Fix the download task

---

src/Sharpliner/AzureDevOps/VariablesReference.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
tests/Sharpliner.Tests/AzureDevOps/Model/VariableSerializationTests.cs

Change built-in variables to strong-typed objects to benefit from the new Macro / Runtime syntaxes

Change built-in variables to strong-typed objects

---

src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ParameterReference.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/VariableReference.cs
src/Sharpliner/AzureDevOps/Model/BuildResource.cs
src/Sharpliner/AzureDevOps/Model/ContainerReference.cs
src/Sharpliner/AzureDevOps/Model/ContainerResource.cs
src/Sharpliner/AzureDevOps/Model/JobBase.cs
src/Sharpliner/AzureDevOps/Model/PackageResource.cs
src/Sharpliner/AzureDevOps/Model/Pool.cs
src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
src/Sharpliner/AzureDevOps/Model/ScheduledTrigger.cs
src/Sharpliner/AzureDevOps/Model/Step.cs
src/Sharpliner/AzureDevOps/Model/Strategy.cs
src/Sharpliner/AzureDevOps/Model/Tasks/BashTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/Builders/BashTaskBuilder.cs
src/Sharpliner/AzureDevOps/Model/Tasks/Builders/PowerShellTaskBuilder.cs
src/Sharpliner/AzureDevOps/Model/Tasks/CheckoutTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/DownloadTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/PowerShellTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/PublishTask.cs
src/Sharpliner/AzureDevOps/Model/Tasks/ScriptTask.cs
src/Sharpliner/AzureDevOps/Model/VariableDefinition.cs
src/Sharpliner/AzureDevOps/Model/WebhookResource.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionedTests.cs
tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
tests/Sharpliner.Tests/AzureDevOps/ParameterReferenceTests.cs
tests/Sharpliner.Tests/AzureDevOps/VariableReferenceTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt

This adds the possibility to use `variables['foo']` in place of other types. It also makes it possible to use the if statement everywhere.
Resolves #266

Allow variable/parameter expressions everywhere

---

docs/AzureDevOps/DefinitionReference.md
src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedExtensions.cs
src/Sharpliner/AzureDevOps/EachExpression.cs
src/Sharpliner/AzureDevOps/Model/ContainerResource.cs
src/Sharpliner/AzureDevOps/Model/JobBase.cs
src/Sharpliner/AzureDevOps/Model/Step.cs
src/Sharpliner/AzureDevOps/Model/WebhookResource.cs
src/Sharpliner/AzureDevOps/Pipeline.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/EachExpressionTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt

Nested each blocks are not working yet but merging this to unblock a feature request
https://github.com/sharpliner/sharpliner/issues/281

Add a support for `${{ each }}` expressions

---

src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ElseCondition.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ElseExpressionTests.cs
tests/Sharpliner.Tests/AzureDevOps/Pipelines/MockPipeline.cs
tests/Sharpliner.Tests/PublicApiExport.txt

https://github.com/sharpliner/sharpliner/issues/284
Allows to use `Else` out of context for instance in input parameters.

Add support for a stand-alone else statement

---

src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ParameterReference.cs
src/Sharpliner/AzureDevOps/Model/Tasks/CheckoutTask.cs
src/Sharpliner/AzureDevOps/TemplateDefinition.cs
tests/Sharpliner.Tests/AzureDevOps/ParameterReferenceTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt

Allows to inject `${{ parameters.foo }}` into almost any place (all where we have `Conditioned<T>`)
#318

Allow template parameter reference everywhere

---

.github/workflows/codeql-analysis.yml
Directory.Build.props
docs/AzureDevOps/GettingStarted.md
eng/PublicApiExporter/PublicApiExporter.csproj
eng/Sharpliner.CI/ProjectBuildSteps.cs
eng/Sharpliner.CI/Sharpliner.CI.csproj
eng/pipelines/pr.yml
eng/pipelines/publish.yml
global.json
src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
src/Sharpliner/AzureDevOps/Model/DeploymentJob.cs
src/Sharpliner/AzureDevOps/Model/Job.cs
src/Sharpliner/AzureDevOps/Model/JobBase.cs
src/Sharpliner/AzureDevOps/Model/LifeCycleHook.cs
src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
src/Sharpliner/AzureDevOps/Pipeline.cs
src/Sharpliner/Common/IDefinitionValidation.cs
src/Sharpliner/GlobalSuppressions.cs
src/Sharpliner/Sharpliner.csproj
src/Sharpliner/SharplinerPublisher.cs
tests/E2E.Tests/ProjectUsingTheLibrary/E2E.Tests.ProjectUsingTheLibrary.csproj
tests/E2E.Tests/ProjectUsingTheLibrary/ProjectTestDefinition.cs
tests/E2E.Tests/ProjectUsingTheLibraryNuGet/E2E.Tests.ProjectUsingTheLibraryNuGet.csproj
tests/E2E.Tests/ProjectUsingTheLibraryNuGet/NuGetTestDefinition.cs
tests/E2E.Tests/SharplinerLibrary/E2E.Tests.SharplinerLibrary.csproj
tests/Sharpliner.Tests/AzureDevOps/Model/VariableSerializationTests.cs
tests/Sharpliner.Tests/GlobalSuppressions.cs
tests/Sharpliner.Tests/Sharpliner.Tests.csproj

Adds the 9.0 target and also gets rid of most of the compiler messages.
The SDK version is now read from `global.json` file and inserted to YAML from there.

Update repo to .NET 9.0

---

src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedExtensions.cs
src/Sharpliner/AzureDevOps/Model/VariableDefinition.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
tests/Sharpliner.Tests/AzureDevOps/PipelineVariableTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt

closes #370
this is already supported by the `VariableTemplate` utility method, which follows the convension of the other template methods such as `StageTemplate`, `JobTemplate`, `StepTemplate`

feature: remove confusing Template method

---

src/Sharpliner/AzureDevOps/Pipeline.cs
tests/Sharpliner.Tests/AzureDevOps/ExtendedPipelineTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt

when passing variables to the extends-template parameters, the extends property must be defined after the variables.

bugfix: make extends property appear last in pipelines

---

src/Sharpliner/SharplinerSerializer.cs
tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt

when not using msbuild and the `SharplinerPublisher` entry-point for file generation we need a public API for serializing classes that extend from `PipelineBase`
FYI @trevorlacey-msft

feature: create a public API for SharplinerSerializer

---

src/Sharpliner/PublishDefinitions.cs
src/Sharpliner/SharplinerPublisher.cs
tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt

these two files are covered by our integration tests and not the unit-tests, so no coverage collected for these
before:
| Module     | Line   | Branch | Method |
|-------------|-------|---------|----------|
| Sharpliner | 66.76% | 60.23% | 61.65% |
after:
| Module     | Line   | Branch | Method |
|-------------|-------|---------|----------|
| Sharpliner | 70.49% | 67.89% | 62.24%
next PR will remove the dead-code we have in `Condition.cs` (internal classes)

chore: Add [ExcludeFromCodeCoverage] attribute to PublishDefinitions and SharplinerPublisher classes

---

eng/DocsGenerator/Program.cs
eng/Sharpliner.CI/ProjectBuildSteps.cs
src/Sharpliner/SharplinerPublisher.cs

This allows Sharpliner to use the RelativeToGitRoot Path Type [on a Git Worktree](https://git-scm.com/docs/git-worktree).  Git Worktrees do not contain a .git Directory, however, they contain a .git file, which is used as a sort of "pointer" file to the main checkout.  Looking for both this file as well as the directory covers both scenarios.

Fix: RelativeToGitRoot for git worktrees.

---

src/Sharpliner/AzureDevOps/Model/Environment.cs
tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
tests/Sharpliner.Tests/Verified/AzureDevOps/TemplateTests.Job_Typed_Template_Definition_Serialization_Test.verified.txt

Currently, when making a deploy job and setting the environment, if we set Tags, they are set like this:
```
environment:
tags:
- tag1
- tag2
```
The issue is, Azure expects this to be a comma delimited string.  This fix makes it so we would instead get this:
```
environment:
tags: tag1, tag2
```

Fix: Environment tags in deploy jobs

---

src/Sharpliner/AzureDevOps/PublicDefinitions.cs
src/Sharpliner/AzureDevOps/TemplateDefinition.cs
tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
tests/Sharpliner.Tests/Verified/AzureDevOps/TemplateTests.Stage_Typed_Template_Definition_Relative_To_Git_Serialization_Test.verified.txt

Currently, in Azure DevOps when we are referencing TemplateDefinitions, we are not taking into account if the file path of the template definition is meant to be relative to the git root.  This means when we reference a template that is being saved in `template/run-git.yaml`, and we attempt to reference it later in a pipeline that exists at `yaml/main-pipeline.yaml`, we create this output in `main-pipeline.yaml`:
```
- template: template/run-git.yaml
```
The reason this is an issue is because when we run `yaml/main-pipeline.yaml`, it will attempt to call that template relative to itself, starting at `yaml`, leading to the wrong area.  To fix this, when a template is relative to the git root, Azure DevOps expects it to begin with `/`, looking like this:
```
- template: …
```

Fixed: Git Relative Templates Not Referenced Correctly

---

src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
src/Sharpliner/AzureDevOps/IfCondition.cs
tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
tests/Sharpliner.Tests/Verified/AzureDevOps.ConditionedExpressions/ConditionalsTests.ConditionedValueWithElseIf_Test.verified.txt

While working with Sharpliner I noticed there was no way to invoke an ${{ elseif }} call.  This update adds .ElseIf as a Conditioned object, which will allow for elseifs like so:
```
If.Equal("A", "B")
.Pool(new HostedPool("pool-A")
{
Demands = { "SomeProperty -equals SomeValue" }
})
.ElseIf.Equal("C", "D")
.Pool(new HostedPool("pool-B"))
```
outputs:
```
${{ if eq('A', 'B') }}:
name: pool-A
demands:
- SomeProperty -equals SomeValue
${{ elseif eq('C', 'D') }}:
name: pool-B
```
I've updated a test that was meant to do ElseIf statements to utilize this.

Elseif condition
