- src/Sharpliner/GitHubActions/Environment.cs
- src/Sharpliner/GitHubActions/Job.cs
- src/Sharpliner/GitHubActions/Workflow.cs
- tests/Sharpliner.Tests/GitHub/JobTests.cs
- tests/Sharpliner.Tests/GitHub/WorkflowTests.cs
Few things need documentation. I need to see how they'll work. Specially with the If condition.
> [Model] Add jobs to github action model.

- azure-pipelines.yml
- src/Sharpliner/PipelineDefinitionBase.cs
Adds a header to the generated YAML file and lets you override the contents
> Add modifiable YAML header

- src/Sharpliner.Tools/PublishPipelines.cs
- src/Sharpliner/AzureDevOps/AzureDevOpsPipeline.cs
- src/Sharpliner/AzureDevOps/AzureDevOpsPipelineDefinition.cs
- src/Sharpliner/AzureDevOps/IDependsOn.cs
- src/Sharpliner/AzureDevOps/Job.cs
- src/Sharpliner/AzureDevOps/Stage.cs
- src/Sharpliner/ConditionedDefinitions/ConditionedDefinition.cs
- src/Sharpliner/PipelineDefinitionBase.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionalVariableTests.cs
- tests/Sharpliner.Tests/AzureDevOps/MockPipeline.cs
- tests/Sharpliner.Tests/AzureDevOps/PipelineValidationTests.cs
- tests/Sharpliner.Tests/AzureDevOps/TestPipeline.cs
- tests/Sharpliner.Tests/AzureDevOps/VariableSerializationTests.cs
Adds the validation step to pipeline publishing and validates some basic properties of `dependsOn` for Stages and Jobs
> Add pipeline validation (for dependsOn)

- README.md
- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Model/PrTrigger.cs
- src/Sharpliner/AzureDevOps/Model/ScheduledTrigger.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/AzureDevOps/TemplateParameter.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/TriggerSerializationTests.cs
This should be the last missing models from AzDO
Resolves #82
> [AzureDevOps] Add model for scheduled triggers

- src/Sharpliner/PublishPipelines.cs
> Log validation exception's message only

- README.md
- docs/AzureDevOps/GettingStarted.md
> Fix examples in README / Getting Started

- src/Sharpliner/build/Sharpliner.targets
Add a human readable error explaining why building Sharpliner in VS does not work
#108
> Print better error when building Sharpliner project in VS

- src/Sharpliner/build/Sharpliner.targets
> Fix MSBuild target not running

- README.md
- docs/AzureDevOps/DefinitionCollections.md
- docs/AzureDevOps/DefinitionReference.md
- docs/AzureDevOps/GettingStarted.md
- eng/Sharpliner.CI/InstallDotNetTemplate.cs
- eng/Sharpliner.CI/PublishPipeline.cs
- eng/Sharpliner.CI/PullRequestPipeline.cs
- eng/Sharpliner.CI/TestPipelines.cs
- eng/pipelines/pr.yml
- eng/pipelines/publish.yml
- eng/pipelines/templates/install-dotnet-runtime.yml
- eng/pipelines/templates/install-dotnet-sdk.yml
- eng/pipelines/test/ubuntu-20.04.yml
- eng/pipelines/test/windows-2019.yml
- src/Sharpliner/AzureDevOps/PipelineDefinition.cs
- src/Sharpliner/AzureDevOps/PipelineDefinitionCollection.cs
- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/AzureDevOps/TemplateDefinitionCollection.cs
- src/Sharpliner/ISharplinerDefinition.cs
- src/Sharpliner/ISharplinerDefinitionCollection.cs
- src/Sharpliner/PublishDefinitions.cs
- src/Sharpliner/SharplinerSerializer.cs
This is a major piece of new functionality that lets people generate definitions dynamically.
You no longer need to override a class to create a definition, the new API lets you define a set of data objects that will end up producing a YAML fine each.
This should prove helpful when creating a large number of similar YAML files.
Resolves #134
> Add collection definitions

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionBuilder.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
> Allow mixing conditions and strings and any number of `and`/`or` parameters

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedDictionary.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedList.cs
- src/Sharpliner/AzureDevOps/Model/ContainerReference.cs
- src/Sharpliner/AzureDevOps/Model/ContainerResource.cs
- src/Sharpliner/AzureDevOps/Model/Step.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
- src/Sharpliner/AzureDevOps/Template.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/AzureDevOps/TemplateParameter.cs
- src/Sharpliner/AzureDevOps/TemplateParameters.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
This enables expressions such as these:
```yaml
template: template1.yaml
parameters:
some: value
${{ if eq(variables['Build.Reason'], 'PullRequest') }}:    <------ conditioned item
pr: true
other: 123
```
> Allow conditioned dictionary keys and values

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/Model/Step.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/VariableSerializationTests.cs
- Also fix conditions in `When()` statement
> Make Variables() macro avilable outside of If statement

- README.md
- docs/AzureDevOps/DefinitionReference.md
- docs/AzureDevOps/GettingStarted.md
- eng/Sharpliner.CI/InstallDotNetTemplate.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
- src/Sharpliner/AzureDevOps/Model/Step.cs
- src/Sharpliner/AzureDevOps/Template.cs
- src/Sharpliner/SharplinerSerializer.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
- tests/Sharpliner.Tests/AzureDevOps/LibraryTests.cs
- tests/Sharpliner.Tests/AzureDevOps/PipelineValidationTests.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
> Use `${{ else }}` expression in Azure Pipelines

- src/Sharpliner/PublishDefinitions.cs
> Simplify loading assemblies

- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPublishCoreCliTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/DotNetCoreCliTests.cs
> fix(DotNetPublishCoreCliTask): public -> publish

- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/Validation/RepositoryCheckoutValidation.cs
- src/Sharpliner/AzureDevOps/Validation/ValidationsExtensions.cs
- src/Sharpliner/SharplinerConfiguration.cs
- tests/Sharpliner.Tests/AzureDevOps/Validation/RepositoryCheckoutsValidationTests.cs
> Add validation for repository checkouts

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedExtensions.cs
- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- tests/Sharpliner.Tests/AzureDevOps/LibraryTests.cs
> Fix job library referencing

- README.md
- docs/AzureDevOps/GettingStarted.md
- eng/Sharpliner.CI/Configuration.cs
- src/Sharpliner/SharplinerConfiguration.cs
- src/Sharpliner/SharplinerPublisher.cs
Adds hooks that are called during the YAML publish process
#188
> Add publish process hooks

- README.md
- src/Sharpliner/GitHubActions/Concurrency.cs
- src/Sharpliner/GitHubActions/Container.cs
- src/Sharpliner/GitHubActions/Defaults.cs
- src/Sharpliner/GitHubActions/Environment.cs
- src/Sharpliner/GitHubActions/Event.cs
- src/Sharpliner/GitHubActions/GitHubActionsPipelineDefinition.cs
- src/Sharpliner/GitHubActions/Job.cs
- src/Sharpliner/GitHubActions/Manual.cs
- src/Sharpliner/GitHubActions/Permissions.cs
- src/Sharpliner/GitHubActions/Runner.cs
- src/Sharpliner/GitHubActions/Service.cs
- src/Sharpliner/GitHubActions/Step.cs
- src/Sharpliner/GitHubActions/Strategy.cs
- src/Sharpliner/GitHubActions/Trigger.cs
- src/Sharpliner/GitHubActions/Webhook.cs
- src/Sharpliner/GitHubActions/Workflow.cs
API is currently hidden to not confuse users until we get to a more complete state
> Hide GitHub Actions from public API

- .github/workflows/codeql-analysis.yml
CodeQL can't use .NET 7.0 so we need to do with this one only
> Target .NET 6.0 in CodeQL only

- README.md
> Add instructions for developing Sharpliner

- src/Sharpliner/AzureDevOps/Model/Pool.cs
Issue #203 => Add implicit cast from string to Pool (resolves to HostedPool with vmImage).
> Fix Issue #203 (Implict cast from string to Pool)

- .editorconfig
- docs/AzureDevOps/DefinitionReference.md
- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/AzureDevOps/TemplateParameter.cs
- src/Sharpliner/SharplinerPublisher.cs
- tests/Sharpliner.Tests/AzureDevOps/PipelineParameterTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Pipelines/XHarnessPipeline.cs
Adds support for https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script
Resolves #208
> Add pipeline parameters

- src/Sharpliner/Sharpliner.csproj
- This broke with .NET 7.0 preview 5
- Should keep working with the old one as well
> Fix including of YamlDotNet into nupkg

- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/DotNetTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetRestoreCoreCliTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/DotNetCoreCliTests.cs
> Set `feedsToUse` automatically when `nugetConfigPath` is specified

- src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
> Do not validate repository resource name

- src/Sharpliner/AzureDevOps/Pipeline.cs
> Allow `pool` property directly on pipeline

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionBuilder.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/StringCondition.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/VariableSerializationTests.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
StringCondition class for wrapping strings in quotes.
This class is to be inherited by String-type conditions such as Contains, StartsWith and EndsWith.
See issue #227
> Wrap string condition expressions in apostrophes automatically

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
> Include default values for parameters when one is set

- .github/workflows/codeql-analysis.yml
- eng/Sharpliner.CI/ProjectBuildSteps.cs
- eng/pipelines/pr.yml
- eng/pipelines/publish.yml
- tests/Sharpliner.Tests/PublicApiChangeTest.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
- tests/Sharpliner.Tests/Sharpliner.Tests.csproj
This adds a tests that validates whether there are no unwanted public API changes in the main library
> Check all public API changes with a test

- src/Sharpliner/AzureDevOps/Model/Tasks/CheckoutTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
- tests/Sharpliner.Tests/PublicApiChangeTest.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Fix `fetchDepth` default of checkout task

- src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
> Fix XML docs for repository resources

- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedList.cs
- tests/Sharpliner.Tests/AzureDevOps/LibraryTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add implicit cast from collections into `ConditionedList<T>`

- src/Sharpliner/AzureDevOps/ConditionedExpressions/ParameterReference.cs
- src/Sharpliner/SharplinerSerializer.cs
- tests/Sharpliner.Tests/AzureDevOps/ParameterReferenceTests.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
Resolves https://github.com/sharpliner/sharpliner/issues/255
> Allow using parameter reference anywhere

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- tests/Sharpliner.Tests/AzureDevOps/PipelineParameterTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
Attempt to add support for #259
> Added support list object parameter

- src/Sharpliner/AzureDevOps/LockBehaviour.cs
- src/Sharpliner/AzureDevOps/Model/Stage.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/SharplinerSerializer.cs
- src/Sharpliner/YamlStringEnumConverter.cs
- tests/Sharpliner.Tests/AzureDevOps/PipelineLockBehaviorTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Support for LockBehavior

- src/Sharpliner/AzureDevOps/Model/Environment.cs
- src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/CheckoutTask.cs
- tests/Sharpliner.Tests/PublicApiChangeTest.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
Using the new converter from #263
> Use new enum converter where possible

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
> Fix publish task with empty name

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
> Fix serialization of a generic task without display name

- src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/PipelineResourceSerializationTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Serialize repository resource always

- src/Sharpliner/AzureDevOps/Pipeline.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add the `appendCommitMessageToRunName` pipeline field (#277

- docs/AzureDevOps/GettingStarted.md
- eng/Sharpliner.CI/PublishPipeline.cs
- eng/pipelines/publish.yml
- src/Sharpliner/AzureDevOps/Model/Extends.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- tests/Sharpliner.Tests/AzureDevOps/ExtendedPipelineTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
Resolves https://github.com/sharpliner/sharpliner/issues/283
> Add support for the `extends` definition

- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- tests/Sharpliner.Tests/AzureDevOps/ExtendedPipelineTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Parameterize ExtendsPipelineDefinition

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Make FlattenDefinitions public

- src/Sharpliner/AzureDevOps/Pipeline.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Make `PipelineBase.Validations` public

- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/DotNetTaskBuilder.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/DotNetCoreCliTests.cs
> DotNetInstallBuilder.FromGlobalJson sets useGlobalJson input

- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishTestResultsTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/PublishTestResultsTaskTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add model for PublishTestResults@2

- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishCodeCoverageResultsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishTestResultsTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/PublishCodeCoverageResultsTaskTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/PublishTestResultsTaskTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Pipelines/XHarnessPipeline.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add model for PublishCodeCoverageResults@2

- src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/CopyFilesTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/CopyFilesTaskTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add model for CopyFiles@2

- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/ArchiveFilesTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/CopyFilesTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DeleteFilesTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/ArchiveFilesTaskTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/DeleteFilesTaskTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add model for ArchiveFiles@2 and DeleteFiles@1

- src/Sharpliner/AzureDevOps/Model/Tasks/CheckoutTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> Add the `fetchTags` property to the `checkout` task

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
- src/Sharpliner/AzureDevOps/Model/InclusionRule.cs
- src/Sharpliner/AzureDevOps/Model/PackageResource.cs
- src/Sharpliner/AzureDevOps/Model/Resources.cs
- src/Sharpliner/AzureDevOps/Model/Trigger.cs
- src/Sharpliner/AzureDevOps/Model/Uses.cs
- src/Sharpliner/AzureDevOps/Model/VariableDefinition.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/AzureDevOps/Validation/DependsOnValidation.cs
- src/Sharpliner/AzureDevOps/VariablesReference.cs
- src/Sharpliner/Common/IDefinitionValidation.cs
- src/Sharpliner/TargetPathType.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> docs: improve csharp docs

- eng/Sharpliner.CI/PublishPipeline.cs
- eng/Sharpliner.CI/PullRequestPipeline.cs
- eng/pipelines/pr.yml
> devops: collect code coverage

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
removed ~80 public API's
closes #330 
related #325
> feature: make AzureDevOps ConditionedExpressions internal

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
- src/Sharpliner/AzureDevOps/EachExpression.cs
- src/Sharpliner/AzureDevOps/Model/Pool.cs
- src/Sharpliner/AzureDevOps/PipelineDefinitionCollection.cs
- src/Sharpliner/AzureDevOps/TemplateDefinitionCollection.cs
- src/Sharpliner/ISharplinerDefinitionCollection.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
- Made `EachExpression` internal
- Made the ctor of `EachBlock` internal
> docs: more docs

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedDictionary.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedList.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
- src/Sharpliner/AzureDevOps/IfCondition.cs
- src/Sharpliner/AzureDevOps/IfStringCondition.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/VariableSerializationTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
How can these be used? (no usage in the code)
- `IfCondition Equal(IfCondition condition)`
- `IfCondition NotEqual(IfCondition condition)`
- `IfConditionBuilder<T>.Equal(string)`
Related #325
> docs: conditions

- src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
https://github.com/sharpliner/sharpliner/pull/336
> Remove unused `IfCondition` ctors

- src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> chore: remove unused IfConditionBuilder<T> method

- src/Sharpliner/AzureDevOps/ConditionedExpressions/ParameterReference.cs
- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- src/Sharpliner/Common/Model/Tasks/TaskBuilderBase.cs
- src/Sharpliner/MultilineStringEmitter.cs
- src/Sharpliner/SharplinerConfiguration.cs
- src/Sharpliner/SharplinerSerializer.cs
- src/Sharpliner/YamlStringEnumConverter.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
https://github.com/sharpliner/sharpliner/issues/325
> Add more XML docs and make several classes internal

- Directory.Packages.props
- src/Sharpliner/YamlStringEnumConverter.cs
this also fixes some flakiness in the tests
see https://github.com/aaubry/YamlDotNet/issues/921
> chore: update yamldotnet to 16.1.3

- src/Sharpliner/AzureDevOps/Model/IDependsOn.cs
- src/Sharpliner/AzureDevOps/Model/NoopJob.cs
- src/Sharpliner/AzureDevOps/Model/PipelineResource.cs
- src/Sharpliner/AzureDevOps/Model/PipelineTrigger.cs
- src/Sharpliner/AzureDevOps/Model/PrTrigger.cs
- src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
- src/Sharpliner/AzureDevOps/Model/ScheduledTrigger.cs
- src/Sharpliner/AzureDevOps/PipelineDefinitionCollection.cs
- src/Sharpliner/AzureDevOps/TemplateDefinitionCollection.cs
- src/Sharpliner/AzureDevOps/VariablesReference.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
related to #325
down to ~120 warnings, only for the task types
> docs: complete core API's

- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/ScriptTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/ScriptTask.cs
- src/Sharpliner/AzureDevOps/Validation/RepositoryCheckoutValidation.cs
- src/Sharpliner/AzureDevOps/Validation/ValidationsExtensions.cs
- src/Sharpliner/SharplinerConfiguration.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Resources/test-script
- tests/Sharpliner.Tests/Sharpliner.Tests.csproj
> docs: for steps.script

- README.md
> chore: fix azure-pipelines link

- src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
> docs: AzureDevOpsTask

- src/Sharpliner/AzureDevOps/Model/Tasks/BashTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/DownloadTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/DownloadTask.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> docs: download

- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/PowerShellTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/PwshTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/PowerShellTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> docs: powershell & pwsh

- src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/ArchiveFilesTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/CopyFilesTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DeleteFilesTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishCodeCoverageResultsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishTestResultsTask.cs
> docs: ArchiveFiles and misc

- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/DotNetTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetBuildCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPackCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPublishCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPushCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetRestoreCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetTestCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/UseDotNetTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/Marketplace/DotNetCoreCliTests.cs
> docs: dotnet

- eng/Sharpliner.CI/PublishPipeline.cs
- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Builders/PublishTaskBuilder.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/PublishTask.cs
- src/Sharpliner/Sharpliner.csproj
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> docs: publish-task

- src/Sharpliner/AzureDevOps/Model/VariableDefinition.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/VariableSerializationTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> feature: Variable as reference

- README.md
- docs/AzureDevOps/DefinitionReference.md
- docs/AzureDevOps/GettingStarted.md
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
- src/Sharpliner/AzureDevOps/Model/VariableDefinition.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- tests/Sharpliner.Tests/AzureDevOps/StrongTypedTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> docs: variable as reference

- docs/AzureDevOps/DefinitionReference.md
- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> feature: enum parameters

- src/Sharpliner/SharplinerPublisher.cs
- tests/E2E.Tests/ProjectUsingTheLibrary/ProjectTestDefinition.cs
> feature: Support definition classes without parametersless constructor

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionExtensions.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ConditionedExtensions.cs
- src/Sharpliner/AzureDevOps/Model/VariableDefinition.cs
- tests/Sharpliner.Tests/AzureDevOps/PipelineVariableTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> feature: support passing enum values to variables

- src/Sharpliner/AzureDevOps/PublicDefinitions.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/AzureDevOps/TypedTemplateUtils.cs
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> feature: extends template definition

- docs/AzureDevOps/DefinitionReference.md
- tests/Sharpliner.Tests/AzureDevOps/TemplateTests.cs
> Add documentation for strong-typed templates

- docs/AzureDevOps/DefinitionReference.md
- eng/DocsGenerator/DefinitionReference.template.md
- tests/Sharpliner.Tests/AzureDevOps/Docs/DefinitionReferenceTests.cs
> docs: generate DefinitionReference

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/ConditionalsTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt
> feature: boolean parameter reference condition

- Directory.Packages.props
- src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/NotConditionHelper.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/BashTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/DownloadTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/NuGetPackCommandTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/PublishTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/ScriptTask.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/GitHubActions/Model/Manual.cs
- src/Sharpliner/GitHubActions/Model/Permissions.cs
- src/Sharpliner/GitHubActions/Model/Webhook.cs
- src/Sharpliner/MultilineStringEmitter.cs
- src/Sharpliner/Require.cs
- src/Sharpliner/Sharpliner.csproj
- src/Sharpliner/build/Sharpliner.props
- tests/Sharpliner.Tests/PublicApiExport.txt
see https://dotnet.microsoft.com/en-us/platform/dotnet-standard#versions
netstandard 2.0 will work for netframework as well
> feature: support netstandard2.0

- Directory.Packages.props
- src/Sharpliner/AzureDevOps/ConditionedExpressions/IfConditionBuilder.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/NotConditionHelper.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/BashTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/DownloadTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/NuGetPackCommandTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/PublishTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/ScriptTask.cs
- src/Sharpliner/AzureDevOps/Parameter.cs
- src/Sharpliner/AzureDevOps/Pipeline.cs
- src/Sharpliner/AzureDevOps/TemplateDefinition.cs
- src/Sharpliner/GitHubActions/Model/Manual.cs
- src/Sharpliner/GitHubActions/Model/Permissions.cs
- src/Sharpliner/GitHubActions/Model/Webhook.cs
- src/Sharpliner/MultilineStringEmitter.cs
- src/Sharpliner/Require.cs
- src/Sharpliner/Sharpliner.csproj
- src/Sharpliner/build/Sharpliner.props
- tests/Sharpliner.Tests/PublicApiExport.txt
Reverts sharpliner/sharpliner#399
This is breaking #397 we need to make sure this is done correctly
> Revert "feature: support netstandard2.0"

- src/Sharpliner/AzureDevOps/Model/RepositoryResource.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/PipelineResourceSerializationTests.cs
- tests/Sharpliner.Tests/Verified/AzureDevOps/PipelineResourceSerializationTests.RepositoryResource_Serialization_Test.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps/PipelineResourceSerializationTests.ResourcePipeline_Serialization_Test.verified.txt
> tests: resources test cases

- src/Sharpliner/AzureDevOps/AzureDevOpsDefinition.cs
- src/Sharpliner/AzureDevOps/Model/IDependsOn.cs
- src/Sharpliner/AzureDevOps/Model/JobBase.cs
- src/Sharpliner/AzureDevOps/Model/Stage.cs
- src/Sharpliner/AzureDevOps/Validation/DependsOnValidation.cs
- tests/Sharpliner.Tests/AzureDevOps/Validation/DependsOnValidationTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps.Validation/DependsOnValidationTests.ConditionedDependsOn_Validation_Test.verified.txt
> feature: allow setting dependsOn to a parameters and support serializing as a single value when possible

- README.md
- Sharpliner.sln
- eng/DocsGenerator/README.template.md
- eng/Sharpliner.CI/PullRequestPipeline.cs
- eng/pipelines/pr.yml
- src/Sharpliner/PublishDefinitions.cs
- src/Sharpliner/build/Sharpliner.targets
- tests/E2E.Tests/ProjectUsingTheLibrarySkipPublish/E2E.Tests.ProjectUsingTheLibrarySkipPublish.csproj
- tests/E2E.Tests/ProjectUsingTheLibrarySkipPublish/ProjectTestDefinition.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
> feature: skip msbuild yaml generation

- src/Sharpliner/AzureDevOps/Model/Tasks/AzureDevOpsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/DownloadTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/ArchiveFilesTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPackCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPublishCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetPushCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetRestoreCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/DotNetTestCoreCliTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishCodeCoverageResultsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/PublishTestResultsTask.cs
- src/Sharpliner/AzureDevOps/Model/Tasks/Marketplace/UseDotNetTask.cs
- src/Sharpliner/EnumUtils.cs
- src/Sharpliner/YamlStringEnumConverter.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
> feature: introduce a GetEnum & SetProperty in AzureDevOpsTask

- README.md
- docs/AzureDevOps/DefinitionCollections.md
- docs/AzureDevOps/DefinitionReference.md
- docs/AzureDevOps/GettingStarted.md
- eng/DocsGenerator/DefinitionCollections.template.md
- eng/DocsGenerator/DefinitionReference.template.md
- eng/DocsGenerator/GettingStarted.template.md
- eng/DocsGenerator/README.template.md
Improve grammar and fix a few minor typos
> Fix grammar and spelling

- src/Sharpliner/AzureDevOps/Model/Stage.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/StageTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps/StageTests.ResourcePipeline_Serialization_Test.verified.txt
And add DisplayAs method
Fixes #424
> Allow Stage.DisplayName to be conditional

- docs/AzureDevOps/DefinitionReference.md
- src/Sharpliner/AzureDevOps/EachExpression.cs
- tests/Sharpliner.Tests/AzureDevOps/ConditionedExpressions/EachExpressionTests.cs
- tests/Sharpliner.Tests/AzureDevOps/Docs/DefinitionReferenceTests.cs
- tests/Sharpliner.Tests/Verified/AzureDevOps.ConditionedExpressions/EachExpressionTests.Each_Expression_Test.verified.txt
Resolves https://github.com/sharpliner/sharpliner/issues/426
> Fix removal of `${{}}` in each expressions

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
removed dead-code
continuation of #432
> chore: Remove unused condition classes from Condition.cs

- docs/AzureDevOps/DefinitionReference.md
- eng/DocsGenerator/DefinitionReference.template.md
- src/Sharpliner/AzureDevOps/ConditionedExpressions/Condition.cs
- src/Sharpliner/AzureDevOps/Model/Step.cs
- tests/Sharpliner.Tests/AzureDevOps/Docs/DefinitionReferenceTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps.Docs/DefinitionReferenceTests.ClassicPipelineSteps_Serialization_Test.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps.Docs/DefinitionReferenceTests.NuGet_Test.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps.Docs/DefinitionReferenceTests.Serialize_ConditionedExpressionsPipeline_Test.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps.Docs/DefinitionReferenceTests.ShorthandPipelineSteps_Serialization_Test.verified.txt
> feat: Use ParameterReference with TimeoutInMinutes Property

- src/Sharpliner/AzureDevOps/ConditionedExpressions/Conditioned.cs
- src/Sharpliner/AzureDevOps/ConditionedExpressions/ParameterReference.cs
- tests/Sharpliner.Tests/AzureDevOps/ParameterReferenceTests.cs
- tests/Sharpliner.Tests/Verified/AzureDevOps/ParameterReferenceTests.PipelineParameter_Serialization_Test.verified.txt
Resolves https://github.com/sharpliner/sharpliner/issues/440
> Fix parameter usage inside `if` blocks

- src/Sharpliner/AzureDevOps/Model/Tasks/CheckoutTask.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/Tasks/TaskBuilderTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps/TaskBuilderTests.Serialize_Checkout_Builder_Test.verified.txt
Updated the Checkout Task to include the following new options:
- PersistCredentials
- SparseCheckoutDirectories
- SparseCheckoutPatterns
- WorkspaceRepo
> Updated CheckoutTask

- docs/AzureDevOps/DefinitionReference.md
- eng/DocsGenerator/DefinitionReference.template.md
see here https://github.com/Meir017/sharpliner/blob/docs/definition-reference/docs/AzureDevOps/DefinitionReference.md#marketplace-tasks
FYI @flcdrg
> docs: nicer marketplace tasks and add nuget link for jfrog

- src/Sharpliner/AzureDevOps/Model/Stage.cs
- tests/Sharpliner.Tests/AzureDevOps/Model/StageTests.cs
- tests/Sharpliner.Tests/PublicApiExport.txt.verified.txt
- tests/Sharpliner.Tests/Verified/AzureDevOps/StageTests.ResourcePipeline_Serialization_Test.verified.txt
> Add pool to stage

- eng/Sharpliner.CI/Sharpliner.CI.csproj
- tests/E2E.Tests/ProjectUsingTheLibrary/E2E.Tests.ProjectUsingTheLibrary.csproj
Avoid issues when target uses powershell default profile
> Update targets to use -noprofile
